services:

  db:
    container_name: mariadb-12.1.1-noble-rc
    image: mariadb:12.1.1-noble-rc
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: v8
    ports:
      - 3308:3306

  adminer:
    container_name: adminer-5.4.0-standalone
    image: adminer:5.4.0-standalone
    restart: always
    ports:
      - 9080:8080
  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
      # Add 127.0.0.1: prefix for localhost-only access (recommended for security)
      - 9081:80
      # Change the number before : to the port the SMTP server should be accessible on
      # Add 127.0.0.1: prefix for localhost-only access (recommended for security)
      - 9025:25
